### PR TITLE
Trying to remove exlicit dependency on Data::Printer, Carp::Always; fixing Couchbase::Document (?)

### PR DESCRIPTION
**Pull request by ivulfson**

### CODE REVIEW

**Comment by mnunberg** [comment]
I'm still not sure how you're getting the XSAccessor warning. My 'IDE' (Komodo) tells me something as well, but I can't reproduce it with real Perl

**Comment by ivulfson** [comment]
I'm replicating it on RHEL 6.4 64-bit and on Xubuntu 14.04 LTS.  Steps to replicate:

# edit `lib/Couchbase/Document.pm` (in this pull request), comment out `replace => 1` line
# edit `lib/Couchbase/Document.pm`, add `use blib;` on top of it
# Do this:
```
perl Makefile.PL
$ perl -cw lib/Couchbase/Document.pm 
Cannot replace existing subroutine 'value' in package 'Couchbase::Document' with an XS implementation. If you wish to force a replacement, add the 'replace => 1' parameter to the arguments of 'use Class::XSAccessor::Array'. at lib/Couchbase/Document.pm line 15.
BEGIN failed--compilation aborted at lib/Couchbase/Document.pm line 23.
```

**Comment by ivulfson** [comment]
So, it's not RHEL-specific, but I have Class::XSAccessor::Array 1.19 on both RHEL and Xubuntu boxes.

**Comment by ivulfson** [comment]
And lastly, I have all of these installed: JSON, JSON::PP, JSON::XS, and JSON::MaybeXS.

**Comment by ivulfson** [comment]
Actually, no, that still fails to install.  cpan2rpm adds perl(Carp::Always) and perl(Data::Printer) dependencies.

**Comment by mnunberg** [comment]
Is there a pragma that `cpan2rpm` can use to _ignore_ a specific module?

**Comment by ivulfson** [comment]
Using `--no-requires 'perl(Data::Printer),perl(Carp::Always)'` on cpan2rpm works.  Insanity...  Sorry for all the back and forth.

**Comment by mnunberg** [comment]
The Class::XSAccessor issue seems to be fixed in the current version - it was a matter of `Couchbase::Document` recursively including itself somehow..

**Pull request closed without merging**
