### PR TITLE
Fixing a warning with old MakeMaker, also perltidy; bump version

### PR DESCRIPTION
**Pull request by ivulfson**
The TEST_REQUIRES was added in 6.64 of ExtUtils::MakeMaker.  Also, some versions of ExtUtils::MakeMaker have underscores, i.e. 6.55_02.

* fixed the TEST_REQUIRES warning
* perltidy the WriteMakefile call
* removed duplicate VERSION_FROM
* bumped version number from 2.0.2 to 2.0.3

### CODE REVIEW

**Comment by mnunberg** [comment]
Hrm. This won't merge -- I guess try to rebase && resubmit?

**Comment by ivulfson** [comment]
Merge conflicts...  Bah!  Damn you, git!  Damn you to hell.

**Comment by mnunberg** [comment]
No, the build is failing because the mock isn't up to date (I need to push a newer version): https://travis-ci.org/mnunberg/perl-Couchbase-Client/builds/57554209

**Comment by mnunberg** [comment]
You'd need to do something like:

```
git fetch upstream #assume upstream is this repo
git rebase -i upstream/master # rebase your master branch; resolve conflicts
git push --force origin master # where origin is your fork
```

**Comment by ivulfson** [comment]
My `git` foo is not nearly strong enough. :)

**Comment by ivulfson** [comment]
Rebase comes up with noop, and push claims that everything is up to date.  I just pushed another commit (perltidy Makefile.PL), to see if it helps.

**Comment by ivulfson** [comment]
Another push, went back to 2.0.2.

**Comment by mnunberg** [comment]
Alrighty, I'll just do this for you and save you the pain.

**Comment by mnunberg** [comment]
Done.

**Comment by ivulfson** [comment]
Awesome.  Thanks!

When do you think you'll have 2.0.3 finalized?

**Comment by mnunberg** [comment]
There's a few more stuff I'd like to add, but I think this is sufficient. I'll leave the rest of the stuff for another version.

**Pull request closed without merging**
